name: release_jobs

on: [push]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull_requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  